### ISSUE TITLE
Can't login after 0.8.1.12

### ISSUE THREAD

**Issue by thasigan** [twrecked/hass-aarlo#1040]
aarlo Component Setup
Error: sse-error=HTTPError
Traceback (most recent call last):
File "/usr/local/lib/python3.13/site-packages/pyaarlo/backend.py", line 621, in _sse_main
self._event_client = SSEClient(
~~~~~~~~~^
self._arlo,
^^^^^^^^^^^
...<3 lines>...
timeout=self._arlo.cfg.stream_timeout,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
)
^
File "/usr/local/lib/python3.13/site-packages/pyaarlo/sseclient.py", line 55, in init
self._connect()
~~~~~~~~~~~~~^^
File "/usr/local/lib/python3.13/site-packages/pyaarlo/sseclient.py", line 74, in _connect
self.resp.raise_for_status()
~~~~~~~~~~~~~~~~~~~~~~~~~~^^
File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://my.arlo.com//hmsweb/client/subscribe

If error persists you might need to change config and restart.

**Comment by twrecked** [comment]
Look at the solution here.

https://github.com/twrecked/hass-aarlo/issues/1033#issuecomment-2641169619

**Comment by gebla** [comment]
There was the fix. In my aarlo.yaml I had a host reference. Deleting the host reference fixed it:

 You should remove the host line from the config. The default is now myapi.arlo.com.

**Comment by thasigan** [comment]
Thank you. I notice that version 0.8.1.13 fixes everything. However I have user_agent pointing to "arlo" and not Linux. Is this right?

I also have a host line in my aarlo.yaml file should I change this to myapi.arlo.com or remove the host line altogether?

**Comment by twrecked** [comment]
You can remove the host line, _aarlo_ will use the correct default.

You can leave the user agent as `arlo`, it is fixed for now.

**Comment by thasigan** [comment]
Apologies I'm not winning here. Check both issues reported. My original issue above is sorted but now getting this after following instructions above:

aarlo Component Setup
Error: login failed: 403 - possible cloudflare issue
If error persists you might need to change config and restart.

My aarlo.yaml looks like this:
version: 1
aarlo:
  #host: https://my.arlo.com/
  #backend: sse
  user_agent: arlo


I'm using the 0.8.1.13 version.
There's nothing for aarlo in my configuration.yaml

I've tried user_agent: linux
I've tried host: myapi.arlo.com 

Please help.

**Comment by twrecked** [comment]
Can you post some of the debug logs? I can't tell much from the a single line, it could be a lot of different things.

**Comment by thasigan** [comment]
@twrecked I deleted the integration and reinstalled. Reconfigured and all seems good.

Not the best solution but it worked

**Comment by twrecked** [comment]
Odd. I guess something was cached. Glad it's working now.
