### ISSUE TITLE
Constant authentication requests since last update

### ISSUE THREAD

**Issue by garybrowngeo** [twrecked/hass-aarlo#1046]
Since the update I am getting constant emails notify me of one time code and new login almost every minute! Has something changed in the last updates? Is there a way to stop this?

**Comment by Phoenix-DH** [comment]
Same here, but I have nothing in the logs.

My config:
`version: 1
aarlo:
  mqtt_host: mqtt-cluster-z1.arloxcld.com
  user_agent: linix `

**Comment by twrecked** [comment]
Arlo changed the backend around. Can you upload some logs?

**Comment by garybrowngeo** [comment]
[home-assistant_2025-02-13T09-59-20.066Z.log](https://github.com/user-attachments/files/18781770/home-assistant_2025-02-13T09-59-20.066Z.log)

This is my latest log file - I have rolled back to 0.8.1.11 at the end of the logs to try and remediate just in case this looks weird!

**Comment by Phoenix-DH** [comment]
I am not at home was only wondering why there are so many mails.

**Comment by garybrowngeo** [comment]
The rollback seems to have stipped the mails for now so could be the user agent change causing arlo to think theres a new device all the time?

**Comment by garybrowngeo** [comment]
The issue seems to have started about 06:52 this morning.

**Comment by Phoenix-DH** [comment]
Will try, thanks.

**Comment by twrecked** [comment]
They've changed the general timeouts to 30 minutes and this includes the access token. It used to be 2 weeks. This is the
same on the web browser.

I need to modify the login code to "trust" the Arlo session and stop the emails happening - this should be possible. For now I think you are going to get those messages every half an hour.

I'll take a look at it today.

**Comment by Phoenix-DH** [comment]
I think the value 25 hsd no effect.

Thanks for your work.

**Comment by twrecked** [comment]
I realised you're still going to get the emails but it should have stopped the errors.

**Comment by yongfg** [comment]
Just realized they change the access token expiration to 2 hours. This is what I got when inspecting the login from an incognito window. So Im sure this is not related to how we mock the payload
```
{
    "meta": {
        "code": 200
    },
    "data": {
        "expiresIn": 1739498798,
        "mfa": true,
        "_type": "AccessTokenV2",
        "authenticated": 1739491598,
        "issued": 1739491598,
        "userId": "...",
        "token": "...",
        "authCompleted": true,
        "MFA_State": "ENABLED",
        "browserAuthCode": "..."
    }
}
```

First of all this will break the intention of the check session we do now:
`get_new_session = days_until(self._expires_in) < 2`

Secondly, not sure if this is related to many issues we've been experiencing recently.

**Comment by twrecked** [comment]
@yongfg  that is exactly the problem

## The way this used to work was

On the first login:
- we login
- we do our 2fa
- we get an authentication token which had a timeout of 14 days
- we validate the token

For logins with in the next 12 days:
- we logged
- we revalidate the token

For logins within the 12 days we didn't need to ask for a 2fa code.

## What changed

But with the new back end changes _arlo_ has reduced the token timeout to 2 hours (it was actually 30 minutes earlier today). So once that token expires we need to get use 2fa to get another token.

## What I'm looking at

I'm testing a _pyaarlo_ branch that makes the component mock the web browser even more closely. With the new changes:

On the first login
- we login
- we do our 2fa
- we get an authentication token which has a timeout of 2 hours
- we validate the token
- **we tell _arlo_ to trust this browser**

On subsequent logins:
- we login
- if we are on a trusted browser we get a new token **without** 2fa
  - we validate the token
- if the trust has expired we start 2fa again
  - we do our 2fa
  - we get an authentication token which had a timeout of 2 hours
  - we validate the token
  - **we tell _arlo_ to trust this browser**
 
The branch is working pretty well but I'll run some more test tonight. Once this workaround is in place I'm going to revisit and refactor this code, it started off simple and has morphed into quite the lump of spaghetti code over time.

**Comment by yongfg** [comment]
Haha totally, I was also messing the code in the similar direction but got no luck. I tried to inspect if they have some token exchange logic or if this field `browserAuthCode` could be helpful. But I'm so glad you figured out it's the trust of the browser, like the page user has to click on trust right. This also means we need to maintain the same browser user agent across different sessions.

Looking forward to the fix and I'm willing to help test and clean up if needed! Thank you

**Comment by yongfg** [comment]
Im seeing a new update for the pyaarlo repo. Thank you for the push! I'm wondering if there's an efficient way to test this. I kinda don't want to always wait for 2 hours before figuring out if the changes works

**Comment by twrecked** [comment]
@yongfg you can set `reconnect_every=15` to force a disconnect every 15 minutes and it will try and login again

The disconnect mechanism is different but the overall effect is the same.

**Comment by twrecked** [comment]
This should be fixed in v0.8.1.15 if people want to give it a try. 

I've had to modify the authentication code and I've tested as thoroughly as I can on my setups. But experience has shown _Arlo_ to be an odd beast so if you run into issues please post some debug logs here.

You can return to v0.8.1.41.1 and it will use the old authentication mechanism.

**Comment by yongfg** [comment]
@twrecked From my understanding of the code, it looks like we always try to do auth with username and password. And for the happy path, we don't have to do 2FA. My question is, does it mean that at least the username and password should always be available? Like we can't silently refresh the access token without the username and password?

**Comment by twrecked** [comment]
Good questions. My goal here was to get it working but it's strained the current code to breaking point.

So I don't know the answer just yet but I suspect as long as the browser token is valid we might be able  to skip to login. But I'm just guessing.

Once I've tidied the state machine I should have a better understanding and I'll give it a try.

**Comment by Phoenix-DH** [comment]
Will give it a try today with the latest release.
One question:
Keep reconnect_every: 25 in the yaml or remove?

**Comment by hceuterpe** [comment]
I'm still getting regular app approval prompts in less than an hour apart...

**Comment by twrecked** [comment]
@Phoenix-DH did you find 15? You might need to get HACS to update its information

@hceuterpe Can you attach some logs.

**Comment by Phoenix-DH** [comment]
Yes, just did the update and removed the lines in the config.
Will give feedback.

Thanks.

**Comment by twrecked** [comment]
@Phoenix-DH excellent, let me know how it goes

**Comment by Phoenix-DH** [comment]
Again up amd running 👌🏻
Lets see.

Restart 11:16am.

**Comment by twrecked** [comment]
@hceuterpe At the computer now...

- can you double check the installed version? looking at the screenshot above it might be possible to get the wrong one
- if you are good, can you turn on verbose debug and attach some logs, it's the only way I'll be able to see what is going on

**Comment by Phoenix-DH** [comment]
Until now …. No mail … still working.

**Comment by twrecked** [comment]
@hceuterpe can you try the 16 release. It might/should fix it.

**Comment by yongfg** [comment]
@twrecked I did some testing and experiments and it feels like the `pairing call` isn't necessary to refresh the token. I wish to double check this with your discovery.
Here's the timeline of my latest experiment.
```
at 12:25, I did a 2fa with my username, password, and "arlo" user agent. I got a token that expires in 2 hours and saved the following auth info:
{"user_id":"...",
 "web_id":"...",
 "sub_id":"...",
"token":"...",
"expires_in":1739658433,
"browser_auth_code":"...",
"device_id":"..."}

I didn't call the `_pair_auth_code`.

I tested right away that only with the username + password + same user agent, Im able to get a new token successfully.

After 5 hours at 5:10,  I called the auth endpoint simply with username + password + same user agent again, and I got 200 with a new token.
```
So I'm wondering when did you figure out that a call to the pairing endpoint is necessary? Am I doing something wrong here? Let me know if you need more information, Appreciated!

**Comment by twrecked** [comment]
It isn't needed every time. 

The code sets `_auth_needs_pairing` to `False` when the `getFactorId` call returns a 200. And `True` if the same call fails for any reason.

Look for `_auth_needs_pairing`  in the code.

My test system in the basement has reconnected 11 times in the last 23 hours  and hasn't paired once.

**Comment by yongfg** [comment]
Oh I see. Thank you for the explanation. Just verified with incognito that the getFactorId call gives 400 along with a message saying "Browser is not trusted" and this is an indicator of the pairing.

**Comment by Phoenix-DH** [comment]
I have no issues so far, no mails… 

Thanks

**Comment by halytech** [comment]
This seems to work like a charm.  It should be noted that you probably need to be on the latest version of HA (2025.2.4) due to dependencies.  I was slacking on the updates and received a bunch of errors that were caused by python dependencies.

Thanks @twrecked !

**Comment by hceuterpe** [comment]
> This seems to work like a charm. It should be noted that you probably need to be on the latest version of HA (2025.2.4) due to dependencies. I was slacking on the updates and received a bunch of errors that were caused by python dependencies.
> 
> Thanks [@twrecked](https://github.com/twrecked) !

I was able to update using 2025.2.3 without issue.

**Comment by halytech** [comment]
> > This seems to work like a charm. It should be noted that you probably need to be on the latest version of HA (2025.2.4) due to dependencies. I was slacking on the updates and received a bunch of errors that were caused by python dependencies.
> > Thanks [@twrecked](https://github.com/twrecked) !
> 
> I was able to update to .17 using 2025.2.3 without issue.

Ahh I was on January still! That'll learn me! 🤪

**Comment by Phoenix-DH** [comment]
Still no issues as it seems, only saw that today:
Logger: pyaarlo
Source: /usr/local/lib/python3.13/site-packages/pyaarlo/__init__.py:752
First occurred: February 16, 2025 at 4:16:34 PM (16 occurrences)
Last logged: 9:01:48 PM

No devices returned from /hmsweb/v2/users/devices?t=[1739718994127](tel:1739718994127)
event loop closed by server

But I think that is not related.

**Comment by hceuterpe** [comment]
Interesting observation:  Before this with the old behavior, triggering a reload operation with the addon in HA required an app MFA approval.  It now, no longer does.  So indeed this seems to work better even before Arlo changed the old token validity period that started all this.  👍🏻

**Comment by twrecked** [comment]
@hceuterpe It's driven by _Arlo_ servers now. We pair the device and re-pair when we are told to.
