### ISSUE TITLE
Control Panel Lovelace card does not update with current mode

### ISSUE THREAD

**Issue by tyoung560** [twrecked/hass-aarlo#286]
Hi,

Reporting that the control panel card is not updating with current mode after being changed through an automation. I think it's becoming unresponsive after a period of time. Manually arming/disarming through the card will not change anything - restarting Home Assistant fixes it.

**Comment by twrecked** [comment]
I noticed this yesterday and it's fixed by #285 which will be appearing in 0.7 later today.

Arlo changed the way their back end works and it even breaks the MODE tab on my.arlo.com.

**Comment by tyoung560** [comment]
Awesome, thanks for letting me know!

**Comment by twrecked** [comment]
I just released 0.7.0.alpha.8 which should fix this.

**Comment by jwillaz** [comment]
I have noticed for several weeks that after a period of time, the call to arm/disarm Arlo sometimes fails with a "Failed to set mode" error on the **first** attempt.  The **second** and subsequent attempts generally always succeed. 

I am currently on v0.7.0-beta.1, and this still happens periodically. I previously had the **reconnect_every** parameter set to 15, so then I tried setting back to the recommended 90. No difference. Is the connection being explicitly re-established after a failure instance? If so, would it then be possible to "replay" the service call after this happens?

**Comment by rafuz** [comment]
I am also getting "failed to set mode" when calling it from automation.

```
Logger: pyaarlo
Source: custom_components/aarlo/pyaarlo/__init__.py:499
First occurred: 6 agosto 2020, 23:13:12 (7 occurrences)
Last logged: 6:18:01

Failed to set mode.
```

It is quite annoying as it fails when I call it from home/not_home automations and then I have to manually change mode to Arlo even if my main alarm panel in already disarmed.

**Comment by twrecked** [comment]
I think Arlo changed something about their mode API recently. If you are in the modes tab on their website it doesn't get notified when you change the mode from the phone app.

@jwillaz 
Anything in the logs?

@rafuz 
The detected I/O is my issue. I'll take a look at that.
The other problem is coming from Arlo. Can you try your Home Assistant account on the `my.arlo.com` website and see if it works?

**Comment by rafuz** [comment]
I have to stop AArlo if I want to stay logged on the website but I have checked and it works.

**Comment by twrecked** [comment]
@rafuz You ok to turn some debug on and get the traces? Are you specifying the mode api to use in your `aarlo` config?

Does your HA account still have admin access?

**Comment by rafuz** [comment]
Give me instructions and I can comply.
No mode api in config and my HA account had admin access.

**Comment by twrecked** [comment]
Also, what version of Aarlo and Home-Assistant?

My bad, I could have sworn you and I have done the debug thing before...

Add this to `configuration.yaml`:

```yaml
logger:
  default: info
  logs:
    custom_components.aarlo: debug
    pyaarlo: debug
```
And then look in `home-assistant.log`. When you try to change mode you should see something like this when you change mode. Check to see if there any error messages:

```log
2020-08-07 14:05:39 DEBUG (SyncWorker_6) [pyaarlo] Rear Base:new-mode=disarmed,id=mode0                                                               
2020-08-07 14:05:39 DEBUG (SyncWorker_6) [pyaarlo] deduced v2 api                                                                                     
2020-08-07 14:05:39 DEBUG (SyncWorker_6) [pyaarlo] v2 arming

...

2020-08-07 14:05:39 DEBUG (SyncWorker_6) [pyaarlo] request url=https://myapi.arlo.com/hmsweb/users/devices/automation/active
```

**Comment by rafuz** [comment]
In 24 hours happened 4 times.
When retrying to set mode usually it is successfull.

I am using the latest versions available of AArlo and Home Assistant/HassOS on QEMU Platform (Proxmox VE)

```
2020-08-11 08:44:49 DEBUG (MainThread) [custom_components.aarlo.switch] get state Arlo Casa Siren form
2020-08-11 08:44:49 DEBUG (MainThread) [custom_components.aarlo.switch] get state for All Sirens
2020-08-11 08:45:19 DEBUG (MainThread) [custom_components.aarlo.switch] get state Arlo Casa Siren form
2020-08-11 08:45:19 DEBUG (MainThread) [custom_components.aarlo.switch] get state for All Sirens
2020-08-11 08:45:44 DEBUG (ArloBackgroundWorker) [pyaarlo] fast refresh
2020-08-11 08:45:44 DEBUG (ArloBackgroundWorker) [pyaarlo] day testing with 2020-08-11!
2020-08-11 08:45:44 DEBUG (ArloBackgroundWorker) [pyaarlo] pinging Arlo Casa
2020-08-11 08:45:44 DEBUG (ArloBackgroundWorker) [pyaarlo] notify+response running
2020-08-11 08:45:44 DEBUG (ArloBackgroundWorker) [pyaarlo] post+response running
2020-08-11 08:45:45 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloBase/<Removed>/connectionState=available
2020-08-11 08:45:49 DEBUG (MainThread) [custom_components.aarlo.switch] get state Arlo Casa Siren form
2020-08-11 08:45:49 DEBUG (MainThread) [custom_components.aarlo.switch] get state for All Sirens
2020-08-11 08:45:51 INFO (SyncWorker_2) [PyTado.interface] api call result: {"access_token":"<Removed>","token_type":"bearer","refresh_token":"<Removed>","expires_in":599,"scope":"home.user","jti":"<Removed>"}
2020-08-11 08:46:19 DEBUG (MainThread) [custom_components.aarlo.switch] get state Arlo Casa Siren form
2020-08-11 08:46:19 DEBUG (MainThread) [custom_components.aarlo.switch] get state for All Sirens
2020-08-11 08:46:44 DEBUG (ArloBackgroundWorker) [pyaarlo] fast refresh
2020-08-11 08:46:44 DEBUG (ArloBackgroundWorker) [pyaarlo] day testing with 2020-08-11!
2020-08-11 08:46:44 DEBUG (ArloBackgroundWorker) [pyaarlo] pinging Arlo Casa
2020-08-11 08:46:44 DEBUG (ArloBackgroundWorker) [pyaarlo] notify+response running
2020-08-11 08:46:44 DEBUG (ArloBackgroundWorker) [pyaarlo] post+response running
2020-08-11 08:46:45 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloBase/<Removed>/connectionState=available
2020-08-11 08:46:49 DEBUG (MainThread) [custom_components.aarlo.switch] get state Arlo Casa Siren form
2020-08-11 08:46:49 DEBUG (MainThread) [custom_components.aarlo.switch] get state for All Sirens
2020-08-11 08:47:19 DEBUG (MainThread) [custom_components.aarlo.switch] get state Arlo Casa Siren form
2020-08-11 08:47:19 DEBUG (MainThread) [custom_components.aarlo.switch] get state for All Sirens
2020-08-11 08:47:36 INFO (MainThread) [custom_components.aarlo.alarm_control_panel] alarm_set_mode service called
2020-08-11 08:47:36 DEBUG (MainThread) [custom_components.aarlo.alarm_control_panel] Arlo Casa set mode to attivo in casa
2020-08-11 08:47:36 DEBUG (MainThread) [pyaarlo] set:ArloBase/<Removed>/activeSchedule=None
2020-08-11 08:47:36 DEBUG (MainThread) [pyaarlo] Arlo Casa:new-mode=attivo in casa,id=mode3
2020-08-11 08:47:36 DEBUG (MainThread) [pyaarlo] v2 arming
2020-08-11 08:47:36 DEBUG (MainThread) [pyaarlo] post+response running
2020-08-11 08:47:36 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for aarlo doing I/O at custom_components/aarlo/pyaarlo/backend.py, line 79: r = self._session.post(url, json=params, headers=headers, timeout=timeout)
2020-08-11 08:47:36 WARNING (MainThread) [pyaarlo] attempt 1: error in response when setting mode=
{'data': {'error': 'AUTO-5010',
          'message': "Device doesn't belong to the User",
          'reason': "<Removed> doesn't belong to the User / Is not "
                    'provisioned'},
 'success': False}
2020-08-11 08:47:36 DEBUG (MainThread) [pyaarlo] Fetching device list (hoping this will fix arming/disarming)
2020-08-11 08:47:36 DEBUG (MainThread) [pyaarlo] get+response running
2020-08-11 08:47:36 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for aarlo doing I/O at custom_components/aarlo/pyaarlo/backend.py, line 73: r = self._session.get(url, params=params, headers=headers, stream=stream, timeout=timeout)
2020-08-11 08:47:36 ERROR (MainThread) [pyaarlo] Failed to set mode.
2020-08-11 08:47:36 DEBUG (ArloBackgroundWorker) [pyaarlo] job-error=TypeError
2020-08-11 08:47:36 DEBUG (MainThread) [pyaarlo] Giving up on setting mode! Session headers=
{'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json, text/plain, */*', 'Connection': 'keep-alive', 'Auth-Version': '2', 'schemaVersion': '1', 'Host': 'my.arlo.com', 'Content-Type': 'application/json; charset=utf-8;', 'Referer': 'https://my.arlo.com', 'Authorization': '<Removed>'}
2020-08-11 08:47:36 DEBUG (MainThread) [pyaarlo] Giving up on setting mode! Session cookies=
None
```

**Comment by twrecked** [comment]
@rafuz Perfect, thanks. I'll take a look.

**Comment by twrecked** [comment]
Can you try the latest build - 0.7.0.beta.2 - I fixed the mode issue with changes in pull #298

**Comment by rafuz** [comment]
Just installed, I will report back after a while.

**Comment by rafuz** [comment]
Two days and service never failed to set mode. I think it is fixed.

**Comment by jwillaz** [comment]
Ditto. Working great, thanks for the quick fix @twrecked !

**Comment by twrecked** [comment]
Excellent. I'll close this one then.

**Comment by dugancom** [comment]
Having a similar issue, the dashboard card has stopped showing the correct status after a mode change.  The mode does change, but the dashboard only shows the correct status after a restart.
